// <auto-generated />
using System;
using DkaizaProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DkaizaProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521003127_AddRecepcionistaRoleAndPagoValidacion")]
    partial class AddRecepcionistaRoleAndPagoValidacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("DkaizaProject.Models.CategoriaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CategoriasServicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Cortes, peinados y tratamientos capilares",
                            Icono = "fa-cut",
                            Nombre = "Cabello",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Tintes, mechas y balayage",
                            Icono = "fa-palette",
                            Nombre = "Coloración",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Keratina, hidratación y más",
                            Icono = "fa-spa",
                            Nombre = "Tratamientos",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Recogidos, ondas y planchado",
                            Icono = "fa-hand-sparkles",
                            Nombre = "Peinados",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Manicure y pedicure profesional",
                            Icono = "fa-hand-peace",
                            Nombre = "Manos y Pies",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Maquillaje social y profesional",
                            Icono = "fa-brush",
                            Nombre = "Maquillaje",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("DkaizaProject.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstilistaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoraFin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstilistaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("DkaizaProject.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsEstilista")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsRecepcionista")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstilistaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstilistaId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Salon",
                            Email = "admin@salon.com",
                            EsAdmin = true,
                            EsEstilista = false,
                            EsRecepcionista = false,
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Admin",
                            PasswordHash = "$2a$11$eC3MeRvFgm5TqxeMK4xxYuZGPth0aElF2fqklF.G/mQEVZJ3fsbwK",
                            Telefono = "999-999-999"
                        },
                        new
                        {
                            Id = 1000,
                            Apellido = "Dkaiza",
                            Email = "recepcion@dkaiza.com",
                            EsAdmin = false,
                            EsEstilista = false,
                            EsRecepcionista = true,
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Recepcion",
                            PasswordHash = "$2a$11$rImcKUDCn6N6xavnKyabG.NFBP/BWszxCHLiu3IPkVii7A6JUWEC6",
                            Telefono = ""
                        });
                });

            modelBuilder.Entity("DkaizaProject.Models.Estilista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FotoBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("FotoContentType")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoraFinDescanso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraFinTrabajo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraInicioDescanso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraInicioTrabajo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estilistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Especialidad = "Coloración y Balayage",
                            HoraFinDescanso = 13,
                            HoraFinTrabajo = 22,
                            HoraInicioDescanso = 12,
                            HoraInicioTrabajo = 10,
                            Nombre = "María González"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Especialidad = "Cortes y Peinados",
                            HoraFinDescanso = 14,
                            HoraFinTrabajo = 22,
                            HoraInicioDescanso = 13,
                            HoraInicioTrabajo = 10,
                            Nombre = "Laura Fernández"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Especialidad = "Tratamientos y Keratina",
                            HoraFinDescanso = 16,
                            HoraFinTrabajo = 22,
                            HoraInicioDescanso = 15,
                            HoraInicioTrabajo = 10,
                            Nombre = "Carolina Rojas"
                        });
                });

            modelBuilder.Entity("DkaizaProject.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CitaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroOperacion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Validado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValidadoPorClienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("DkaizaProject.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaServicioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImagenBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImagenContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaServicioId");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaServicioId = 1,
                            Descripcion = "Corte personalizado según tu estilo y tipo de cabello",
                            DuracionHoras = 1,
                            Nombre = "Corte de cabello",
                            Precio = 35m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaServicioId = 1,
                            Descripcion = "Corte especial para niños hasta 12 años",
                            DuracionHoras = 1,
                            Nombre = "Corte infantil",
                            Precio = 25m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaServicioId = 1,
                            Descripcion = "Técnica de corte con navaja para texturizar",
                            DuracionHoras = 1,
                            Nombre = "Corte con navaja",
                            Precio = 45m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaServicioId = 2,
                            Descripcion = "Coloración completa con productos de alta calidad",
                            DuracionHoras = 2,
                            Nombre = "Tinte completo",
                            Precio = 90m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaServicioId = 2,
                            Descripcion = "Técnica de iluminación para un look natural",
                            DuracionHoras = 2,
                            Nombre = "Mechas / Balayage",
                            Precio = 110m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaServicioId = 2,
                            Descripcion = "Mechas finas para dar luminosidad",
                            DuracionHoras = 2,
                            Nombre = "Reflejos",
                            Precio = 95m
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaServicioId = 2,
                            Descripcion = "Tintes en colores vibrantes (rosa, azul, morado)",
                            DuracionHoras = 3,
                            Nombre = "Color fantasía",
                            Precio = 130m
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaServicioId = 2,
                            Descripcion = "Neutralización de tonos no deseados",
                            DuracionHoras = 1,
                            Nombre = "Matizado",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaServicioId = 3,
                            Descripcion = "Tratamiento alisante que nutre y repara",
                            DuracionHoras = 2,
                            Nombre = "Alisado keratina",
                            Precio = 130m
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaServicioId = 3,
                            Descripcion = "Tratamiento intensivo para cabello seco",
                            DuracionHoras = 1,
                            Nombre = "Hidratación profunda",
                            Precio = 45m
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaServicioId = 3,
                            Descripcion = "Tratamiento reconstructivo antioxidante",
                            DuracionHoras = 2,
                            Nombre = "Botox capilar",
                            Precio = 120m
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaServicioId = 3,
                            Descripcion = "Reparación de cabello dañado químicamente",
                            DuracionHoras = 2,
                            Nombre = "Reconstrucción capilar",
                            Precio = 110m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaServicioId = 4,
                            Descripcion = "Lavado + peinado profesional",
                            DuracionHoras = 1,
                            Nombre = "Lavado y peinado",
                            Precio = 40m
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaServicioId = 4,
                            Descripcion = "Recogido o semirecogido para ocasiones especiales",
                            DuracionHoras = 2,
                            Nombre = "Peinado de novia",
                            Precio = 80m
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaServicioId = 4,
                            Descripcion = "Ondas definidas o sueltas según tu preferencia",
                            DuracionHoras = 1,
                            Nombre = "Ondas y rulos",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            CategoriaServicioId = 4,
                            Descripcion = "Alisado con plancha y protección térmica",
                            DuracionHoras = 1,
                            Nombre = "Planchado profesional",
                            Precio = 35m
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            CategoriaServicioId = 5,
                            Descripcion = "Limpieza, corte y esmaltado",
                            DuracionHoras = 1,
                            Nombre = "Manicure clásico",
                            Precio = 35m
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            CategoriaServicioId = 5,
                            Descripcion = "Cuidado completo de pies",
                            DuracionHoras = 1,
                            Nombre = "Pedicure clásico",
                            Precio = 40m
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            CategoriaServicioId = 5,
                            Descripcion = "Esmaltado semipermanente en uñas",
                            DuracionHoras = 1,
                            Nombre = "Manicure con gelish",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            CategoriaServicioId = 5,
                            Descripcion = "Esmaltado semipermanente en pies",
                            DuracionHoras = 1,
                            Nombre = "Pedicure con gelish",
                            Precio = 55m
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CategoriaServicioId = 5,
                            Descripcion = "Ambos servicios con descuento especial",
                            DuracionHoras = 2,
                            Nombre = "Combo Manicure + Pedicure",
                            Precio = 65m
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            CategoriaServicioId = 6,
                            Descripcion = "Maquillaje para eventos y ocasiones especiales",
                            DuracionHoras = 1,
                            Nombre = "Maquillaje social",
                            Precio = 60m
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            CategoriaServicioId = 6,
                            Descripcion = "Maquillaje profesional para tu día especial",
                            DuracionHoras = 2,
                            Nombre = "Maquillaje de novia",
                            Precio = 120m
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            CategoriaServicioId = 6,
                            Descripcion = "Diseños creativos y caracterización",
                            DuracionHoras = 2,
                            Nombre = "Maquillaje artístico",
                            Precio = 90m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaServicioId = 3,
                            Descripcion = "Tinte + corte + peinado",
                            DuracionHoras = 3,
                            Nombre = "Tratamiento completo",
                            Precio = 160m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DkaizaProject.Models.Cita", b =>
                {
                    b.HasOne("DkaizaProject.Models.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DkaizaProject.Models.Estilista", "Estilista")
                        .WithMany("Citas")
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DkaizaProject.Models.Servicio", "Servicio")
                        .WithMany("Citas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estilista");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("DkaizaProject.Models.Cliente", b =>
                {
                    b.HasOne("DkaizaProject.Models.Estilista", "Estilista")
                        .WithMany()
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estilista");
                });

            modelBuilder.Entity("DkaizaProject.Models.Pago", b =>
                {
                    b.HasOne("DkaizaProject.Models.Cita", "Cita")
                        .WithOne("Pago")
                        .HasForeignKey("DkaizaProject.Models.Pago", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("DkaizaProject.Models.Servicio", b =>
                {
                    b.HasOne("DkaizaProject.Models.CategoriaServicio", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaServicioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DkaizaProject.Models.CategoriaServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("DkaizaProject.Models.Cita", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("DkaizaProject.Models.Cliente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("DkaizaProject.Models.Estilista", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("DkaizaProject.Models.Servicio", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
